apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
      version: green
  template:
    metadata:
      labels:
        app: fastapi-app
        version: green
    spec:
      containers:
        - name: fastapi
          image: dhiraj918106/fastapi-blue-green-deployment:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
