apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
    version: green  # Change to "green" when switching traffic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
