apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
    version: blue  # Change this to 'green' during traffic switch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
